### ISSUE TITLE
WebSite: 404 for BS web font (woff2) 

### ISSUE THREAD

**Issue by peterblazejewicz** [Microsoft/TypeScriptSamples#135]
This is minor and related to the website assets:
```css
@font-face {
  font-family: 'Glyphicons Halflings';

  src: url('../fonts/glyphicons-halflings-regular.eot');
  src: url('../fonts/glyphicons-halflings-regular.eot?#iefix') format('embedded-opentype'), url('../fonts/glyphicons-halflings-regular.bc0cf52d.woff2') format('woff2'), url('../fonts/glyphicons-halflings-regular.woff') format('woff'), url('../fonts/glyphicons-halflings-regular.ttf') format('truetype'), url('../fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular') format('svg');
}
```
Fro dev console:
```text
GET https://www.typescriptlang.org/assets/fonts/glyphicons-halflings-regular.bc0cf52d.woff2 
```
